@startuml
'https://plantuml.com/class-diagram

class HaloServiceConsumer{
    + getReference(Class<T> clazz): T
}


class HaloServiceProvider{
    + export(Class<T> clazz,(? extends T) impl);
}
@enduml